import mongoose from "mongoose"
const profileSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    location:{
        type:String,
        required:true,
    },
    primaryRole:{
        type:String,
        required:true,
    },
    otherRoles:{
        type:[String],
    },
    aboutMe:{
        type:String,
    },
    experience:{
        type:String,
    },
    college:{
        type:String,
    },
    desiredSalary:{
        type:Number,
        required:true,
    },
    currentSalary:{
        type:Number,
    },
    links:{
        type:[String],
    },
    profilePicture:{
        type:String,
    },
    resume:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
    },
    contactNo:{
        type:String,
        required:true,
    },
    owner:{
        type:mongoose.Schema.ObjectId,
        ref:user
    }
},{
    timestamps:true,
})
export const Profile=mongoose.model("Profile",profileSchema)