import mongoose from "mongoose"
import { User } from "./user.model.js"
const profileSchema=new mongoose.Schema({
    name:{
        type:mongoose.Schema.ObjectId,
        ref:"User"
    },
    location:{
        type:mongoose.Schema.ObjectId,
        ref:"User"
    },
    primaryRole:{
        type:String,
        required:true,
    },
    otherRoles:{
        type:[String],
    },
    aboutMe:{
        type:String,
    },
    experience:{
        type:Number,
    },
    college:{
        type:String,
    },
    desiredSalary:{
        type:Number,
        required:true,
    },
    currentSalary:{
        type:Number,
    },
    links:[
        {
            type:String,
            label:String,
        }
    ],
    profilePicture:{
        type:String,
    },
    resume:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
    },
    contactNo:{
        type:String,
        required:true,
    },
    owner:{
        type:mongoose.Schema.ObjectId,
        ref:"User"
    }
},{
    timestamps:true,
})
export const Profile=mongoose.model("Profile",profileSchema)